Разметка главной страницы
htmlacademy-adaptive/1859049-sedona-25 pull request #2
Opened 2022-04-01 16:37 UTC by AnastasiiaSeed

2022-04-02 11:19 UTC, redsmoke19 requested changes
Настя привет! В целом ты отлично справилась с разметкой главной страницы. Но есть несколько важных замечаний от меня которые нужно доработать) Посмотри их в коде, я постарался все подробно описать) Жду правок

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +        <img src="../source/img/logo.svg" width="185" height="96" alt="Отели Седоны">
У самого логотипа так же должен быть свой класс, и так же по методологии БЭМ. К примеру `main-header__img` 
И так же не забывай, обязательно в конце Alt текста ставить точку `.`

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +        <div class="main-nav__wrapper">
А зачем нам тут нужна дополнительная обертка ?)

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +              <a>Главная</a>
Так же у все ссылок должен быть свой класс. К примеру `site-list__link`.

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +        <div class="index-background">
Все хорошо, но давай мы будем пользоваться более семантическими тегами для блоков. Все независимые блоки будем оборачивать тег `section`, а не `div`. И тут наверно лучше вместо класса `index-background` использовать класс `hero` или `promo`, такой класс мне кажется более подробно подходит для данной секции. И от этого класса внутри данного блока будем выстаивать БЭМ структуру. К примеру `promo__img` и `promo__title` и т.д.)
Т.е. по хорошу у нас должно с этим блоком получиться следующее:
```html
<section class="promo">
    <img class="promo__img" src="" alt="">
    <div class="promo__wrapper">
        <h1 class="promo__title"></h1>
        <p class="promo__text"></p>
    </div>
</section>
```

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +      <div class="advantages-wrapper">
Так же смотри, тут у нас начинается новый независимый блок. Давай обернем его в секцию и задам ему правильный класс, к примеру `advantages`. И уже внутри от него будем выстраивать БЭМ структуру) По примеру выше. Потому что есть сейчас, оно не соответствует БЭМу. Данный блок нужно будет переработать)

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +      <section class="search">
Вот тут правильно, это отдельная секция. Но в ней у тебя классы идут не по БЭМ. Т.е. у тебя есть блок `search` - это Блок, а дочерние - это элементы. Т.е. `search__title`, `search__text` и т.д. Посмотри еще раз часть лекции в которой говорится про БЭМ, что бы лучше его понять, т.к. это вадная тема)

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +      <section class="cart_user">
Опять же, правильно что это у тебя новая секция, но название ее не по БЭМ. Давай дадим этой секции класс `map`, а картинке внутри нее `map__img` - вот так правильно будет по БЭМ

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +          <p>#visitsedona</p>
нужен обязательно класс, так же по БЭМ

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +          <ul class="social__list">
Ты здесь начинаешь использовать новое пространство имен, у тебя есть элемент `social__list` - а блока для этого элемента нет. Посмотри как ты делала в шапке, ты там так же расширяла пространство имен. И там было сделано правильно) Строка 17)

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +        <div class="main-footer__social">
Зачем тут нужна доп. обертка ? Я уверен что она тут лишняя)

2022-04-02 11:19 UTC, redsmoke19 commented on source/index.html
> +          <p>Разработано</p>
Нужен обязательно класс)

2022-04-04 13:00 UTC, AnastasiiaSeed commented on source/index.html
> +        <div class="main-nav__wrapper">
по учебнику было написано, что эта обертка необходимо для скрытия меню.

2022-04-04 14:23 UTC, AnastasiiaSeed commented on source/index.html
> +          <ul class="social__list">
на 100 строке, же начинается новый блок, разве нет?

2022-04-05 06:01 UTC, redsmoke19 requested changes
Нужно еще доработать разметку. Есть ошибки в БЭМ и в структуре размети

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +      <div class="page-container">
Этот класс `page-container` должен оборачивать все содержимое внутри тега main, а он у тебя оборачивает только секцию промо.
Т.е. этот клсс должен обернуть все содержимое в main
```html
<main class="main-container">
    <div class="page-container">
        <!-- Вот тут весь остальной контент - все секции внутри одной обертки -->
    </div>
</main>
```

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <img class="promo-img" src="img/welcome.png" alt="Logo">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <div class="promo-wripper">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <h1 class="promo-title">Седона - небольшой городок в аризоне , <br> заслуживающий большего! </h1>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <p class="promo-text"> Рассмотрим 5 причин, по которым Седона круче, чем Гранд-Каньон</p>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +      <div class="advantages-wrapper">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +      <ul class="advantages_list">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <img src="img/photo-1.jpg" alt="Фото кафе">
Для все картинок нужен свой класс

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <h3 class="advantages-title">Настоящий городок</h3>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <p class="advantages-ordinal-number">-№1-</p>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <p class="advantages-text">Седона не аттракцион для туристов, там течет своя жизнь</p>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <li class="advantages__item card-foto">
А для чего тут второй класс `card-foto` ? Его можно удалить

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <p class="search__text">Укажите предполагаемые даты поездки, <br> и мы покажем вам лучшие предложения гостиниц в Седоне </p>
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <a class="search-link--button" href="#">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <img class="map-img" src="../source/img/map-mobile.jpg" alt="Наше местоположение на карте">
Ошибка БЭМ

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <p class="main-footer__hashtag_hotels">#visitsedona</p>
Ошибка БЭМ - тут нужно так - `main-footer__hashtag-hotels`

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +        <ul class="social social-list">
Снова не много не так. У нас этот списко вложен в блок `main-footer`, поэтому от этого блока мы и должны расширять пространство имен:
```html
<ul class="main-footer__list social"></ul>
```
Вот так будет правильно. И теперь от блока `social` дальше по БЭМ все пошло правильно

2022-04-05 06:01 UTC, redsmoke19 commented on source/index.html
> +          <p class="main-footer__copyright__link">Разработано</p>
Ошибка БЭМ, тут нужно так - `<p class="main-footer__copyright-link">Разработано</p>`

2022-04-05 09:58 UTC, merged